### ISSUE TITLE
Add to README, how to setup local development environment

### ISSUE THREAD

**Issue by pkopac** [pirati-cz/web#4]

**Comment by vencax** [comment]
I appriciate using github. But I dare to say that its aimed for source code maintance. But in this repo is no single line of code. So? :) Any of following issues are useless until the actual source is commited.

**Comment by pkopac** [comment]
You are mistaken, the source code is in the src/ folder. This issue is ergo still valid.
I could also ask Vaclav personally, but hey, it should be written in the README.
